import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { matrix } from "../test/support/endpoint-matrix.mjs";
import { format, resolveConfig } from "prettier";
import assert from "node:assert/strict";
const report = JSON.parse(
  readFileSync(new URL("../docs/qualification-results.json", import.meta.url), "utf8"),
);
const names = [
  ...new Set([...matrix.map((row) => row.name), ...report.cases.map((row) => row.operation)]),
].sort();
const rows = names.map((name) => {
  const samples = report.cases.filter((row) => row.operation === name);
  return `| \`${name}\` | ${matrix.filter((row) => row.name === name).length} | ${samples.filter((row) => row.status === "passed").length} | ${samples.filter((row) => row.status === "failed").length} | ${samples.filter((row) => row.status === "not-run").length} |`;
});
const counts = Object.fromEntries(
  ["passed", "failed", "not-run"].map((status) => [
    status,
    report.cases.filter((row) => row.status === status).length,
  ]),
);
const text = `# Coverage matrix

Generated by \`npm run coverage:report\` from executable cases and the live ledger.
Capture series started: ${report.capturedAt}.

## Coverage meaning

- Every public HTTP resource method is inventoried; adding one without a case fails CI.
- Wire cases cover four leaderboard windows, omitted/boundary limits, encoded
  handles/cursors, six network IDs and token-feed filter combinations.
- Separate tests cross pagination budgets with actual multi-page responses,
  malformed/empty pages, missing/null actors, cancellation, HTTP failures and
  simultaneous 401s across resources with one shared refresh.
- Successful native samples test the production parser. They are not proof of
  all service-supported chains or all parameter combinations.
- Known-negative samples remain failures in the ledger even though replaying the
  expected rejection passes CI. No public contract was weakened for these tests.

Live ledger: **${counts.passed} passed / ${counts.failed} failed / ${counts["not-run"]} not run**.

| Method/capability | Offline wire cases | Live pass | Live fail | Not run |
| --- | ---: | ---: | ---: | ---: |
${rows.join("\n")}

## Remaining gates

See [qualification-results.json](qualification-results.json) for exact cases.
Network samples come from a real trending snapshot, not invented token addresses.
Networks absent from that snapshot are explicitly not qualified.

Activity with a null actor still rejects the entire page (\`invalid_user_id\`);
a small page that happens to contain only attributed actors can succeed.
Actual refresh-token rotation, a real current-account WS activity event and
lossless disconnect recovery remain unqualified. Existing WS traces and synthetic
session/state-machine tests must not be substituted for those live gates.

The public market-subscription API has not been added. Market traces test decoder
shape/order only. No finite suite exhausts arbitrary data, timing or concurrency.
`;
const file = fileURLToPath(new URL("../docs/coverage.md", import.meta.url));
const rendered = await format(text, { ...(await resolveConfig(file)), parser: "markdown" });
if (process.argv.includes("--check"))
  assert.equal(readFileSync(file, "utf8"), rendered, "Run npm run coverage:report");
else writeFileSync(file, rendered);
